FormatVersion: OOS-2019-06-01
Description:
  en: >-
   Use this template to run Ansible playbooks on ECS Instance.
  zh-cn: 使用这个模板执行ECS实例中的AnsibleBook 帮助手册请参考https://yq.aliyun.com/articles/718185
  name-en: ACS-ECS-ApplyAnsiblePlayBooks
  name-zh-cn: 在实例中执行Ansible PlayBook
  categories:
    - run_command
Parameters:
  playbookurl:
    Type: String
    Description:
      en: 'You must specify a URL where the playbook is stored.You can specify the URL in the following formats: http://example.com/playbook.yml'
      zh-cn: 您必须指定用于存储剧本的URL。可以按以下格式指定URL：http://example.com/playbook.yml
    AllowedPattern: '^\s*$|^(http|https)://[^'']*$'
  hosts:
    Type: String
    Description: You must specify a hosts to run ansible playbook
    Default: local
  extravars:
    Type: String
    Description:
      en: 'Additional variables to pass to Ansible at runtime. Enter a space separated list of key/value pairs. For example: color=red flavor=lime'
      zh-cn: 其他变量在运行时传递给Ansible。 输入以空格分隔的键/值对列表。 例如：color = red flavour = lime
    Default: SSM = True
    AllowedPattern: ^$|^\w+\=\S+(\s\w+\=\S+)*$
  check:
    Type: String
    Description:
      en: Use the check parameter to perform a dry run of the Ansible execution.
      zh-cn: 使用check参数执行Ansible执行的空运行。
    AllowedValues:
      - 'True'
      - 'False'
    Default: 'False'
  targets:
    Type: Json
    AssociationProperty: Targets
    AssociationPropertyMetadata:
      ResourceType: 'ALIYUN::ECS::Instance'
  rateControl:
    Description:
      en: Concurrency ratio of task execution.
      zh-cn: 任务执行的并发比率。
    Type: Json
    AssociationProperty: RateControl
    Default:
      Mode: Concurrency
      MaxErrors: 0
      Concurrency: 10
  OOSAssumeRole:
    Description: The RAM role to be assumed by OOS.
    Type: String
    Default: OOSServiceRole
RamRole: '{{ OOSAssumeRole }}'
Tasks:
  - Name: getInstance
    Description:
      en: Views the ECS instances.
      zh-cn: 获取ECS实例。
    Action: 'ACS::SelectTargets'
    Properties:
      ResourceType: 'ALIYUN::ECS::Instance'
      Filters:
        - '{{ targets }}'
    Outputs:
      instanceIds:
        Type: List
        ValueSelector: 'Instances.Instance[].InstanceId'
  - Name: runCommand
    Action: 'ACS::ECS::RunCommand'
    Properties:
      commandContent: |-
        ansible --version;
        if [ $? -ne 0 ]; then
            echo "Ansible is not installed. Please install Ansible and rerun the command" >&2;
            exit 1;
        fi
        if [[ "{{playbookurl}}" =~ ^http* ]]; then
           wget -O playbook.yml '{{playbookurl}}'
           echo $?
           if [ $? -ne 0 ]; then
             echo "There was a problem downloading the playbook. Make sure the URL is correct and that the playbook exists.">&2;
             exit 1;
           fi
        else
            echo "The URL protocal is not http(s).">&2;
            exit 1
        fi
        if  [[ {{check}} == True ]] ; then
           ansible-playbook --check -c {{hosts}} -e {{extravars}} playbook.yml;
        else
           ansible-playbook -c {{hosts}} -e {{extravars}} playbook.yml;
        fi
      instanceId: '{{ ACS::TaskLoopItem }}'
      commandType: RunShellScript
    Loop:
      Items: '{{ getInstance.instanceIds }}'
      RateControl: '{{ rateControl }}'
      Outputs:
        commandOutputs:
          AggregateType: 'Fn::ListJoin'
          AggregateField: commandOutput
    Outputs:
      commandOutput:
        Type: String
        ValueSelector: invocationOutput
Outputs:
  commandOutput:
    Type: String
    Value: '{{ runCommand.commandOutputs }}'

